version: "3.8"
services:
  app:
    build: .
    command: python manage.py migrate
    ports:
      - 5000:5000
    volumes:
      - app-data:/app/data
    command: python app.py
volumes:
  app-data:
